project:
  type: website
  output-dir: docs

website:
  title: "John's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Blog
        menu:
          - text: Overview
            href: Blog.qmd
          - text: Random Forest Tutorial
            href: tutorial.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



